POST http://localhost:3002/exercises
Content-Type: application/json

{
 "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
 "target": 2.5
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
 "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
 "target": "g"
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
 "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
 "target": 
}

###

POST http://localhost:3002/exercises
Content-Type: application/json

{
 "daily_exercises": ["g", 0, 2, 0, 3, 0, 2.5],
 "target": 2
}