GET http://localhost:3003/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2d1c2VyNCIsImlkIjoiNjI2N2JmMGIwNDYxNzIyZGQ0MDNjNTM5IiwiaWF0IjoxNjUxNDc3NDkyLCJleHAiOjE2NTE0ODEwOTJ9.zpP55-LI1XPbDmRe-GWjvII9SboybXMmyBACcRlqg3w
