# Without token
POST http://localhost:3003/api/blogs/62679daf1dc21cab8fa69e92/comments
Content-Type: application/json

{
  "comment": "This is a comment."
}


###


# With token
POST http://localhost:3003/api/blogs/62679daf1dc21cab8fa69e92/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2d1c2VyMSIsImlkIjoiNjI2NzgyMWJjYzI2NzcwNmI5MjFjZDZiIiwiaWF0IjoxNjcyODk5ODM1LCJleHAiOjE2NzI5MDM0MzV9.8jzMwpF8ZWswLAYUeMrGp8pkDWoELeS1D65dT81laS0

{
  "comment": "This is a comment."
}


###


# Another blog
POST http://localhost:3003/api/blogs/63b3f72445cf1e944e5c7f5a/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2d1c2VyMSIsImlkIjoiNjI2NzgyMWJjYzI2NzcwNmI5MjFjZDZiIiwiaWF0IjoxNjcyODk5ODM1LCJleHAiOjE2NzI5MDM0MzV9.8jzMwpF8ZWswLAYUeMrGp8pkDWoELeS1D65dT81laS0

{
  "comment": "Hello, bro!"
}

